# Generated by Django 6.0.4 on 2026-05-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_postheart_user_alter_postlike_user_and_more'),
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
        ),
    ]
