# Generated by Django 6.0.4 on 2026-05-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_initial'),
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chats', to='profile_app.profile', verbose_name='Адмін'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', to='profile_app.profile', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='read_messages', to='profile_app.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profile_app.profile'),
        ),
    ]
