# Generated by Django 6.0.4 on 2026-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verefied',
            new_name='email_verified',
        ),
    ]
