# Generated by Django 6.0.4 on 2026-04-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_email_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
