# Generated by Django 6.0.4 on 2026-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_user_email_code_remove_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_handle',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
