# Generated by Django 6.0.4 on 2026-05-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва альбому')),
                ('theme', models.CharField(blank=True, max_length=50, verbose_name='Тема')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Рік подій')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Чи відображається')),
                ('is_default', models.BooleanField(default=False, verbose_name='Стандартний')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_shown', models.BooleanField(default=True, verbose_name='Чи відображається')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profile_app.album', verbose_name='Альбом')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='Підпис')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка')),
                ('pseudonym', models.CharField(blank=True, max_length=50, verbose_name='Псевдонім')),
                ('is_image_signature', models.BooleanField(default=False, verbose_name='Підпис зображенням')),
                ('is_text_signature', models.BooleanField(default=False, verbose_name='Підпис текстом')),
                ('friends', models.ManyToManyField(blank=True, to='profile_app.profile', verbose_name='Друзі')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='FriendsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='profile_app.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='profile_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='profile_app.profile', verbose_name='Профіль'),
        ),
    ]
