# Generated by Django 4.2.25 on 2026-06-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_is_active_alter_album_id_alter_albumimage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
